name: 'GP Security Scan'
description: 'Scan packages and Docker images uploaded to GitHub Packages'
author: 'WhiteSource'
inputs:
  gp-token:
    description: 'GitHub access token with read/write privileges to GitHub Packages'
    required: true
  ws-destination-url:https://app.whitesourcesoftware.com
      description: 'WS environment destination url'
      required: true
  ws-api-key:b9e6964c7b9f42299b77858299a49a5659e7b345f5974771b89cb155458a99f7
    description: 'WS organization api key'
    required: true
  ws-user-key:a090661cccf04cfe82bd4b3d670bffb9e48e2d4a7bb5441f8d650df7d47bdfec
    description: 'WS user key'
    required: true
  ws-product-key:eb48bff7e5eb4324ae4d306622ab3b51787f74c3774e42b78ef257162a642569
    description: 'WS product key to publish results to'
    required: false
  print-scan-report:
    description: 'Whether to print the results report'
    required: false
    default: false
  actions_step_debug:
    description: 'Whether to print debug logs'
    required: false
    default: false
outputs:
  scan-report-file-path:
    description: 'Path of the scan report file'
  scan-report-folder-path:
    description: 'Path of the folder of the scan report file'
runs:
  using: 'node12'
  main: 'src/main.js'
branding:
  icon: 'shield'
  color: 'purple'
